sudo: required
services:
  - docker
before_install:
  - docker build -t dsavax/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run dsavax/react-test npm test -- --coverage
after_success:
  - docker build -t dsavax/multi-client ./client
  - docker build -t dsavax/multi-nginx ./nginx
  - docker build -t dsavax/multi-server ./server
  - docker build -t dsavax/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push images to the Docker Hub.
  - docker push dsavax/multi-client
  - docker push dsavax/multi-nginx
  - docker push dsavax/multi-server
  - docker push dsavax/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-222040459125
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
